#!/usr/bin/env bash
# Layer 5 (OS/deployment) firewall provisioning — macOS.
# tasks/18-security-zero-egress.md §7 Requirement 5.
#
# Mechanism: pf (Packet Filter) via pfctl, NOT the Application Firewall /
# socketfilterfw (that GUI is inbound-permission-oriented and has no
# outbound-block-except-loopback primitive — docs/security.md layer 5).
#
# Loads a dedicated anchor blocking outbound non-loopback traffic from the
# backend's listening port (config/app.yaml app.port, default 8000).
# Loopback (Ollama :11434, the frontend dev origin, SQLite/Chroma files) is
# never touched by this rule set.
#
# THIS IS A ONE-TIME PROVISIONING STEP. Run the configure mode (no flags)
# once, well before demo day, on the actual reference machine, then leave it
# alone. NEVER run configure mode live during a demo — docs/security.md
# layer 5: "configured and tested well before demo day, never adjusted
# live". The --verify mode is read-only and safe to re-run anytime,
# including on demo day.
#
# The exact anchor syntax below is authored per Task 18's documented intent
# but, per the task file's own "Known Risks", is NOT guaranteed correct by
# this documentation set — hand-verify on the actual M4 Pro before relying
# on it (a wrong rule can break the machine's own legitimate loopback/UI
# traffic).
#
# Usage:
#   sudo ./scripts/configure_firewall_macos.sh            # one-time provisioning
#   ./scripts/configure_firewall_macos.sh --verify         # read-only check, safe anytime

set -euo pipefail

ANCHOR_NAME="com.bulwark.outbound"
ANCHOR_FILE="/etc/pf.anchors/${ANCHOR_NAME}"
BACKEND_PORT="${BULWARK_BACKEND_PORT:-8000}"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: this script is macOS-only (found: $(uname -s)). Use configure_firewall_windows.ps1 on Windows." >&2
  exit 1
fi

usage() {
  echo "Usage: $0 [--verify]"
  echo "  (no args)   Configure the pf anchor. Requires sudo. One-time provisioning only."
  echo "  --verify    Read-only: attempt an outbound connection and report pass/fail. Safe anytime."
}

verify_mode() {
  echo "Verifying outbound-block-except-loopback for backend port ${BACKEND_PORT}..."

  # 1. Loopback must still work (Ollama on 11434).
  if curl -s -o /dev/null -m 3 http://127.0.0.1:11434/api/tags; then
    echo "  [ok] loopback (Ollama :11434) reachable"
  else
    echo "  [warn] loopback (Ollama :11434) not reachable — Ollama may not be running; this is not a firewall failure"
  fi

  # 2. A real outbound attempt from a shell process must fail once the
  #    anchor is loaded. This checks the *rule's effect*, not the backend
  #    process specifically — pf applies at the packet-filter layer, so any
  #    process on this host attempting the scoped traffic pattern is a valid
  #    proxy for "would the backend's own outbound calls be blocked".
  if curl -s -o /dev/null -m 3 https://1.1.1.1 2>/dev/null; then
    echo "  [FAIL] outbound to a public host succeeded — the firewall rule is not active or not effective"
    exit 1
  else
    echo "  [ok] outbound to a public host failed as expected"
  fi

  echo "verify: PASS"
}

configure_mode() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "error: configure mode requires sudo (writes ${ANCHOR_FILE} and loads it via pfctl)." >&2
    echo "       re-run as: sudo $0" >&2
    exit 1
  fi

  echo "Writing pf anchor ${ANCHOR_FILE}..."
  cat > "${ANCHOR_FILE}" <<EOF
# Generated by scripts/configure_firewall_macos.sh — Bulwark zero-egress Layer 5.
# Blocks outbound non-loopback traffic; loopback is always exempt.
block drop out quick inet from any to any
pass out quick inet from any to 127.0.0.0/8
pass out quick inet6 from any to ::1
EOF

  # Idempotent: remove any prior load of this anchor before re-adding
  # (pfctl has no "replace" — flush the anchor's own rules, then reload).
  echo "Loading anchor into pf (idempotent reload)..."
  pfctl -a "${ANCHOR_NAME}" -F all 2>/dev/null || true
  pfctl -a "${ANCHOR_NAME}" -f "${ANCHOR_FILE}"

  # Ensure pf itself is enabled (idempotent — pfctl -e errors harmlessly if
  # already enabled; that's expected and not a failure of this script).
  pfctl -e 2>/dev/null || true

  echo "configured: pf anchor ${ANCHOR_NAME} loaded from ${ANCHOR_FILE}"
  echo "Run '$0 --verify' to confirm the rule is effective."
}

case "${1:-}" in
  --verify)
    verify_mode
    ;;
  "")
    configure_mode
    ;;
  -h|--help)
    usage
    ;;
  *)
    echo "error: unknown argument '$1'" >&2
    usage
    exit 1
    ;;
esac
